name: Auto Build undfeine0man/coolcontrold

on:
  schedule:
    - cron: "0 0 * * *" # 每天凌晨检查一次基础镜像是否有更新
  workflow_dispatch: # 允许你手动点击按钮测试

jobs:
  check-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Docker Login
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v3.0.1
        with:
          base-image: coolercontrol/coolercontrold:latest
          image: undefine0man/coolercontrold:latest
          platforms: linux/amd64
        continue-on-error: true

      # - name: Set build flag
      #   id: decide
      #   run: |
      #     if [ "${{ steps.check.outcome }}" == "success" ] && [ "${{ steps.check.outputs.needs-updating }}" == "true" ]; then
      #       echo "should_build=true" >> $GITHUB_OUTPUT
      #     elif [ "${{ steps.check.outcome }}" == "failure" ]; then
      #       # 失败可能是因为目标镜像不存在，此时应该构建
      #       echo "should_build=true" >> $GITHUB_OUTPUT
      #     else
      #       echo "should_build=false" >> $GITHUB_OUTPUT
      #     fi

      - name: Build and push
        uses: docker/build-push-action@v7.0.0
        with:
          # context: .
          push: true
          tags: undefine0man/coolercontrold:latest
        if: steps.check.outputs.needs-updating == 'true' || steps.check.outputs.needs-building == 'true'
